management:
  server:
    port: 9000
  endpoints.web.exposure.include: env,health,info,metrics,loggers,prometheus
  endpoint.health.show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        resilience4j:
          circuitbreaker:
            calls: true
    web:
      server:
        request:
          autotime:
            enabled: true
      client:
        request:
          autotime:
            enabled: true

server:
  port: 8000

logging:
  level:
    com.zlrx: debug
    org: info
    reactor.netty: info
    reactor.icp: info
    org.springframework.web.servlet.DispatcherServlet: off

resilience4j.circuitbreaker:
  circuit-breaker-aspect-order: 1
  configs:
    default:
      failureRateThreshold: 50
      slowCallRateThreshold: 75
      slowCallDurationThreshold: 800
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 20
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 30s
      eventConsumerBufferSize: 30
      registerHealthIndicator: false
  instances:
    peopleService:
      baseConfig: default
    addressService:
      baseConfig: default
  metrics:
    enabled: true


spring:
  application:
    name: netty-research
  sleuth:
    enabled: true
    reactor:
      instrumentation-type: decorate_queues
    propagation:
      type: b3
    baggage:
      correlation-enabled: true
      tag-fields:
        - request-id
      remote-fields:
        - x-correlation-id
        - x-context-id
        - x-channel-id
        - x-request-tracking-id
      local-fields:
        - correlation-id
        - request-id
      correlation-fields:
        - x-correlation-id
    web:
      client:
        enabled: true
    mongodb:
      enabled: false

