management:
  server:
    port: 9000
  endpoints.web.exposure.include: env,health,info,metrics,loggers,prometheus
  endpoint.health.show-details: ALWAYS

server:
  port: 8000

logging:
  level:
    com.zlrx: debug
    org: info
    reactor.netty: debug
    reactor.icp: debug

spring:
  application:
    name: netty-research
  sleuth:
    enabled: true
    reactor:
      instrumentation-type: decorate_on_each
    propagation:
      type: b3
    baggage:
      correlation-enabled: true
      tag-fields:
        - request-id
      remote-fields:
        - x-correlation-id
        - x-context-id
        - x-channel-id
        - x-request-tracking-id
      local-fields:
        - correlation-id
        - request-id
      correlation-fields:
        - x-correlation-id
    web:
      client:
        enabled: true
