management:
  server:
    port: 9000
  endpoints.web.exposure.include: env,health,info,metrics,loggers,prometheus
  endpoint.health.show-details: ALWAYS
  metrics:
    tags:
      application: ${spring.application.name}
    web:
      server:
        request:
          autotime:
            enabled: true
      client:
        request:
          autotime:
            enabled: true

server:
  port: 8000

logging:
  level:
    com.zlrx: debug
    org: info
    reactor.netty: info
    reactor.icp: info
    org.springframework.web.servlet.DispatcherServlet: off

spring:
  application:
    name: netty-research
  sleuth:
    enabled: true
    reactor:
      instrumentation-type: decorate_queues
    propagation:
      type: b3
    baggage:
      correlation-enabled: true
      tag-fields:
        - request-id
      remote-fields:
        - x-correlation-id
        - x-context-id
        - x-channel-id
        - x-request-tracking-id
      local-fields:
        - correlation-id
        - request-id
      correlation-fields:
        - x-correlation-id
    web:
      client:
        enabled: true
